### ISSUE TITLE
Instructions for Linux Compile not working.

### ISSUE THREAD

**Issue by betstick** [LuxCoreRender/LinuxCompile#10]
I've got a blank Ubuntu 18.04 machine that I used just for this. After you do the first run script and compile LuxCore, you don't get a LuxCore-opencl folder. Instead you get a regular LuxCore folder. When you execute the binaries inside to test scenes, there are no options to use OpenCL GPUs. Otherwise everything else works.
Edit: I did the git pull last night from the link provided in the Wiki: https://wiki.luxcorerender.org/Compiling_LuxCore#Linux

**Comment by Dade916** [comment]
The new unified binaries check at run time if OpenCL and/or CUDA are available and enable/disable the support
accordingly.There is not need anymore of a separate "-opencl" version.  Are you sure to have a working OpenCL driver installed ? Does LuxMark work ?

You should post the complete log output of running "luxcoreui scenes/cornell/cornell.cfg". The important part is:

```
[LuxRays][0.171] OpenCL support: enabled
[LuxRays][0.220] OpenCL Platform 0: Intel(R) CPU Runtime for OpenCL(TM) Applications
[LuxRays][0.220] OpenCL Platform 1: NVIDIA CUDA
[LuxRays][0.220] CUDA support: enabled
[LuxRays][0.220] CUDA support: available
[LuxRays][0.220] CUDA driver version: 10.10
[LuxRays][0.220] CUDA device count: 1
```

"OpenCL support: enabled" will tell you OpenCL has been detected.

**Comment by betstick** [comment]
I see. I was trying to do a compile on a headless system with no GPU. Is this not possible then?

**Comment by Dade916** [comment]
Do you have a working OpenCL installation on the headless system ? They usually require a quite specific setup both for NVIDIA and AMD GPUs.
