### ISSUE TITLE
New dependency for CUDA

### ISSUE THREAD

**Issue by Alpistinho** [LuxCoreRender/LinuxCompile#11]
Hi,

I had also to install the _patchelf_ package in order to compile. Other than that the script ran to completion successfully.

https://github.com/LuxCoreRender/LinuxCompile/blob/c87a50e884bc8c77c41de1f51369a443bbbf6e67/first_run.sh#L5

I believe the package can be added to the line above, right?

Thanks

**Comment by Theverat** [comment]
Done in d11771f6b4f94c0c9ec1fd43500d0e32174513da.

What is the dependency for CUDA? Or was this only about patchelf?

**Comment by Alpistinho** [comment]
Just a compile-time tool dependency =)

Thanks
