### ISSUE TITLE
Could not find Boost

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LinuxCompile#12]
A while ago I tried to compile a different project, which required some special Boost version. So I mucked around with my system's boost installation, and apparently this broke LuxCore compilation.

My system is Ubuntu 20.04.

I am now getting this output:
```
~/P/LinuxCompile (master)> ./build-64-sse2 LuxCore 5
 *** BUILDING FOR X86-64 (SSE2) ***
 * LuxCore static enabled
 * Using GCC compiler
 * Checking distfiles
boost_1_72_0.tar.gz
bzip2-1.0.8.tar.gz
c-blosc-1.17.1-bin.tgz
cuda11.0-nvrtc.tar.gz
embree-3.8.0.x86_64.linux.tar.gz
freetype-2.4.11.tar.bz2
ilmbase-2.2.0.tar.gz
jpegsrc.v9d.tar.gz
libpng-1.6.37.tar.gz
oidn-1.2.1.x86_64.linux.tar.gz
oiio-Release-1.8.13.tar.gz
openexr-2.4.0.tar.gz
qt-5.12.2.tar.gz
tbb2019_20191006oss_lin.tgz
tiff-4.0.9.tar.gz
xz-5.0.5.tar.xz
zlib-1.2.11.tar.gz
 * Done checking distfiles
 * Checking target tree
 * Target tree exists
 * Checking libstdc++
 * Done checking libstdc++
 * Checking python
 * Done checking python
 * Checking LuxMark scenes
 * Done LuxMark scenes
 * Prechecks completed

 * Using Python library path: /home/simon/Projects/LinuxCompile/target-64-sse2/lib/libpython3.8.a
/home/simon/Projects/LinuxCompile/target-64-sse2/lib/libpython3.7.a
 * Using Python include path: /usr/include/python3.8

 * Configuring luxrays luxcore pyluxcore luxcoreui
-- CMake version 3.16.3 detected
-- Single-config generator detected
-- Using build variant: 
-- Available custom configurations in cmake/SpecializedConfig:
--   Config_Dade
--   Config_Linux-Static
--   Config_OSX
--   Config_Windows
-- Using custom build config: cmake/SpecializedConfig/Config_Linux-Static.cmake
-- Using Linux static settings
-- Could NOT find Boost: missing: thread program_options filesystem serialization iostreams regex system python chrono serialization numpy (found /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.56.0"))
-- Re-trying with link static = ON
-- Could NOT find Boost: missing: thread program_options filesystem serialization iostreams regex system python chrono serialization numpy (found /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.56.0"))
-- OpenMP found - compiling with
CMake Error at CMakeLists.txt:105 (MESSAGE):
  --> Could not locate required Boost files - Please check


-- Configuring incomplete, errors occurred!
See also "/home/simon/Projects/LinuxCompile/LuxCore/CMakeFiles/CMakeOutput.log".
See also "/home/simon/Projects/LinuxCompile/LuxCore/CMakeFiles/CMakeError.log".
CMake Warning:
  Value of PYTHON_LIBRARY contained a newline; truncating


 !!! luxrays luxcore pyluxcore luxcoreui configuration failed
```

I find the whole situation quite strange. Since LuxCore downloads its own boost_1_72_0.tar.gz, I would expect it to compile and store this in some location that is completely independent from the rest of my system. And I would expect the compilation script to then use its own compiled boost, not some globally installed system boost.

Also, on the one hand it says it could not find Boost, but then it says 
> found suitable version "1.71.0", minimum required is "1.56.0"

So I am confused now, and have no idea how to fix this.
I tried running the compilation script from Stage 1.1 - boost, but it did not solve the problem.

**Comment by Dade916** [comment]
The error is likely to be related to a missing component ("thread program_options filesystem serialization iostreams regex system python chrono", one of them) in your system installation.

What Boost library is found is up to CMake and can be investigated only on your system. The code is here: https://github.com/LuxCoreRender/LuxCore/blob/2e8bf14380df7615c3746eff7ad02b7b983683bc/cmake/Dependencies.cmake#L70 (your find_package() is not finding the right one).

Can't you just uninstall the system Boost ?

Have you deleted your "LuxCore/CMakeCache.txt" before any try ?

**Comment by Theverat** [comment]
> Have you deleted your "LuxCore/CMakeCache.txt" before any try ?

I think so, yes.

> Can't you just uninstall the system Boost ?

I ended up doing this and it "solved" the problem.

However I find it quite bad that the build environment brings its own boost version, but then prefers some random other boost installation if present. What if someone wants to compile other projects besides Lux which require a different boost version? It seems pretty strange behaviour to me.

Thanks for your help.
