### ISSUE TITLE
Travis CI for releases

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LinuxCompile#4]
I just discovered that Travis CI can upload the compiled binaries to create releases on github:
* https://docs.travis-ci.com/user/deployment/releases/
* https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci/33109519#33109519
We could use this to automatically create test builds for people who want to use the bleeding edge binaries without compiling themselves (replacing the old daily builds).
But we could also use this to create final releases.

Now all we need is a cross compiler so Travis can also build Windows binaries for us and we'll never again have to package a release by hand...

**Comment by Dade916** [comment]
It may worth to explore https://www.appveyor.com because they support Windows builds too.

**Comment by Dade916** [comment]
Another interesting option: https://jenkins-ci.org/

**Comment by neo2068** [comment]
Pciccone used Jenkins to build the daily builds.

**Comment by Theverat** [comment]
With acasta69's latest work we can probably close this.
