### ISSUE TITLE
PySide dependency wasn't installing

### ISSUE THREAD

**Issue by aPonza** [LuxCoreRender/LinuxCompile#6]
I wasn't able to install PySide which is a required dependency for LuxCoreRender via your instructions in the README.

The only way to avoid a circular dependency error in pip/pip3 was by installing PySide via "sudo apt-get install python3-pyside". Maybe consider adding this command on the readme as a third option.

**Comment by Dade916** [comment]
What kind of circular dependency did you had try to installing PySide ? And on what Linux distribution ?

**Comment by aPonza** [comment]
I am on Ubuntu 16.04 and the circular dependency involved pip and pip3 both: when using "sudo pip/pip3 install PySide" I was requested to upgrade my pip version, while trying to upgrade via "pip install pip --user --upgrade" the error was "ImportError: cannot import name 'main'". Finally, to fix the import error, the solution was again asking me to upgrade my pip version. The same loop was happening with pip3

**Comment by Dade916** [comment]
Ok, thanks, I added a note about Ubuntu.

**Comment by Dade916** [comment]
I guess we can now close this.
