### ISSUE TITLE
How to create a debug build?

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LinuxCompile#7]
Can I create a debug build with the LinuxCompile build scripts?
I'm especially interested in a debug build of the pyluxcore.so library.

**Comment by Dade916** [comment]
You have to define (like in https://github.com/LuxCoreRender/LuxCore/blob/252b56565d793edc64ef74e2efd281f7864d4cc6/cmake/SpecializedConfig/Config_Dade.cmake#L59):

`SET(CMAKE_BUILD_TYPE "Debug")`

It should be possible to do it from cmake command line or by adding the "SET()" to cmake files or creating a new LuxCore/cmake/SpecializedConfig/Config_BYOB.cmake

**Comment by Theverat** [comment]
For now I have changed it in `LuxCore-opencl/cmake/SpecializedConfig/Config_Linux-Static.cmake`, seems to work. Thanks!
